language: go

services:
  - docker

script:
  - make artifacts version=${TRAVIS_TAG}

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true