language: go

services:
  - docker

stages:
  - Tests
  - Release
  - Deploy

jobs:
  include:
    - stage: Tests
      name: "Testing"
      if: (branch = master) OR (tag IS present) OR (type = pull_request)
      script: make test
    - stage: Release
      name: "Releasing a new version"
      if: tag IS present
      script:
        - make artifacts version=${TRAVIS_TAG} skip-test=1
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: $GH_TOKEN
        body: "v${TRAVIS_TAG}"
        file_glob: true
        file: "artifacts/*"
        on:
          tags: true
    - stage: Release
      name: "Publishing docker image"
      if: tag IS present
      script:
        - make image skip-test=1
        - make push-image username="$DOCKER_USERNAME" password="$DOCKER_PASSWORD"
    - stage: Deploy
      name: "Deploying to Heroku"
      if: tag IS present
      script:
        - make heroku-image heroku_app=$HEROKU_APP
        - ./heroku-container-release.sh